#!/usr/bin/env bash
# Boot the DeepSeek Harness web UI with the local dsn-finance plugin.
#
# Multi-app safety (this machine hosts several dsh plugin apps in parallel):
#   * each app gets its own $DSH_HOME  → own profiles/sessions/storages
#   * each app gets its own port       → default 0 (OS-assigned, printed on boot)
#   * plugin deps + LLM provider live in the profile layer (generated overlay),
#     never in the shared ~/.dsh home
#   * dataDir is per app ($DSH_HOME/data), not the package-relative default
#
# Node is pinned: dsh needs `import.meta.main` (^22.19 or >=24.2); 24.0/24.1
# make `dsh` exit silently, so pick a binary that can actually run it and fail
# loudly otherwise.
#
#   ./scripts/dev_web.sh
#   DSH_PORT=3180 ./scripts/dev_web.sh
#   DSH_NODE=/path/to/node ./scripts/dev_web.sh
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$PWD"

# ---- 1. per-app home -------------------------------------------------------
export DSH_HOME="${DSH_HOME:-$ROOT/.dsh-home}"
mkdir -p "$DSH_HOME"

# ---- 2. pinned Node --------------------------------------------------------
supports_import_meta_main() {
  [ -n "${1:-}" ] && [ -x "$1" ] || return 1
  "$1" --input-type=module -e 'process.exit(import.meta.main === undefined ? 1 : 0)' >/dev/null 2>&1
}

WANT="$(tr -d '[:space:]' < "$ROOT/.nvmrc" 2>/dev/null || echo 22.22.2)"
candidates() {
  [ -n "${DSH_NODE:-}" ] && echo "$DSH_NODE"
  for dir in "$HOME/.workbuddy/binaries/node/versions" "$HOME/.nvm/versions/node"; do
    [ -d "$dir" ] || continue
    # newest matching $WANT first, then newest overall
    ls -d "$dir"/"$WANT"*/bin/node "$dir"/*/bin/node 2>/dev/null || true
  done
  for c in /opt/homebrew/opt/node@22/bin/node /opt/homebrew/opt/node/bin/node /opt/homebrew/bin/node "$(command -v node || true)"; do
    [ -n "$c" ] && echo "$c"
  done
}

NODE_BIN=""
while read -r candidate; do
  if supports_import_meta_main "$candidate"; then NODE_BIN="$candidate"; break; fi
done < <(candidates)

if [ -z "$NODE_BIN" ]; then
  echo "dsh needs Node ^22.19 or >=24.2 (import.meta.main); none found (want $WANT)." >&2
  echo "Set DSH_NODE=/path/to/node, or install one into ~/.workbuddy/binaries/node/versions." >&2
  exit 1
fi
export PATH="$(dirname "$NODE_BIN"):$PATH"
echo "node: $NODE_BIN ($("$NODE_BIN" -v))  ·  DSH_HOME: $DSH_HOME"

DSH_BIN="$ROOT/node_modules/@deepseek-ai/dsh/lib/bin.js"
[ -f "$DSH_BIN" ] || { echo "missing $DSH_BIN — run npm install first" >&2; exit 1; }

# ---- 3. profile + port -----------------------------------------------------
PROFILE="${DSH_PROFILE:-web}"
HOST="${DSH_HOST:-127.0.0.1}"
PORT="${DSH_PORT:-0}"   # 0 = OS-assigned: no cross-app port collision

# ---- 4. profile layer: plugin entry (absolute paths) + LLM provider --------
WESTOCK_BIN="${WESTOCK_BIN:-}"
if [ -z "$WESTOCK_BIN" ]; then
  for c in "$DSH_HOME/bin/westock" "$HOME/.westock/bin/westock" "$(command -v westock || true)"; do
    [ -n "$c" ] && [ -x "$c" ] && { WESTOCK_BIN="$c"; break; }
  done
fi
export WESTOCK_BIN

OVERLAY="$DSH_HOME/dsn-finance.overlay.yml"
{
  echo "# Generated by scripts/dev_web.sh — per-app profile overlay (do not commit)."
  echo "# Plugin dependencies, dataDir, data sources and the LLM provider all live"
  echo "# in this profile layer so other dsh apps on this machine stay untouched."
  # id-targeted config override: `dsh plugin add` already registers the entry,
  # so this layer only supplies this app's configuration (no duplicate entry).
  echo "- id: dsn-finance"
  echo "  config:"
  echo "    cacheTtlSec: 300"
  echo "    requestGapMs: 3000"
  echo "    httpTimeoutMs: 30000"
  echo "    logLevel: ${DSN_FINANCE_LOG_LEVEL:-info}"
  echo "    dataDir: $DSH_HOME/data"
  echo "    westock:"
  echo "      enabled: true"
  if [ -n "$WESTOCK_BIN" ]; then echo "      binPath: $WESTOCK_BIN"; else echo "      binPath: ''"; fi
  echo "      timeoutMs: 20000"
  echo "      autoUpgrade: false"
  echo "    research:"
  echo "      enabled: true"
  echo "      dir: $DSH_HOME/data/research"
  # volatile：面板默认「浮层抽屉」而非停靠页（停靠页需要宿主 dock 容器，
  # 未选择工作区时会渲染不出来）。可在面板内一键切换。
  echo "    panelDocked: false"
  echo ""
  echo "# 可选：把宿主 web 搜索切到本插件的免费 meta-search（ddg/python）。"
  echo "# 需要先安装 Python 包 ddgs（pip install ddgs），否则会覆盖宿主默认搜索且二者都不可用；"
  echo "# 确认可用后再取消下面 3 行注释。"
  echo "# - id: web"
  echo "#   config:"
  echo "#     searchProvider: dsn-web-search"
  echo ""
  echo "# LLM provider (OpenAI-compatible gateway) — profile layer only."
  echo "- id: llm-pi-ai"
  echo "  config:"
  echo "    providers:"
  echo "      qwen-local:"
  echo "        displayName: Qwen (本地网关)"
  echo "        api: openai-completions"
  echo "        baseURL: ${LLM_BASE_URL:-http://29.181.193.119:8080/v1}"
  echo "        apiKeyEnv: ${LLM_API_KEY_ENV:-QWEN_API_KEY}"
  echo "        models:"
  echo "          - id: ${LLM_MODEL:-Qwen3.6-35B-A3B}"
  echo "            name: ${LLM_MODEL:-Qwen3.6-35B-A3B}"
  echo "            contextWindow: ${LLM_CONTEXT_WINDOW:-128000}"
  echo "            maxTokens: 8192"
  echo "            input: [text]"
  echo "            reasoningEfforts: false"
  echo "- id: agent-default-model"
  echo "  config:"
  echo "    provider: qwen-local"
  echo "    model: ${LLM_MODEL:-Qwen3.6-35B-A3B}"
} > "$OVERLAY"
echo "overlay: $OVERLAY${WESTOCK_BIN:+  ·  westock: $WESTOCK_BIN}"

# ---- 5. register + boot ----------------------------------------------------
# A fresh $DSH_HOME has no profile yet: create it from the shipped web template.
if [ ! -d "$DSH_HOME/profiles/$PROFILE" ]; then
  echo "creating profile $PROFILE from the shipped web template…"
  "$NODE_BIN" "$DSH_BIN" --profile "$PROFILE" --from-default-profile web --dump-default-config >/dev/null 2>&1 || true
fi

echo "registering plugin in profile $PROFILE …"
"$NODE_BIN" "$DSH_BIN" plugin --profile "$PROFILE" add "$ROOT" >/dev/null

echo "starting: dsh --profile $PROFILE --host $HOST --port $PORT (0 = OS-assigned) --patch overlay"
# The launcher owns --profile/--patch; the app's own flags (--host/--port) follow.
exec "$NODE_BIN" "$DSH_BIN" --profile "$PROFILE" --patch "$OVERLAY" --host "$HOST" --port "$PORT"
